/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * XAxisUnit.java
 *
 * Created on Jun 16, 2010, 3:27:36 PM
 */

package org.jpowder.Analysis;

import javax.swing.JRadioButton;

/**
 *
 * @author Arjeneh
 */
public class XAxisUnit extends javax.swing.JPanel {

    /** Creates new form XAxisUnit */
    public XAxisUnit() {
        initComponents();

    }
    public static JRadioButton getfileNumbRadioButton(){
        return fileNumbRadioButton;
    }
    public static JRadioButton getPressureRadioButton(){
        return PressureRadioButton;
    }
    public static JRadioButton getTempratureRadioButton(){
        return tempratureRadioButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileNumbRadioButton = new javax.swing.JRadioButton();
        PressureRadioButton = new javax.swing.JRadioButton();
        tempratureRadioButton = new javax.swing.JRadioButton();

        buttonGroup1.add(fileNumbRadioButton);
        fileNumbRadioButton.setSelected(true);
        fileNumbRadioButton.setText("File Number");

        buttonGroup1.add(PressureRadioButton);
        PressureRadioButton.setText("Pressure");

        buttonGroup1.add(tempratureRadioButton);
        tempratureRadioButton.setText("Temprature");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileNumbRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PressureRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempratureRadioButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNumbRadioButton)
                    .addComponent(PressureRadioButton)
                    .addComponent(tempratureRadioButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JRadioButton PressureRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JRadioButton fileNumbRadioButton;
    private static javax.swing.JRadioButton tempratureRadioButton;
    // End of variables declaration//GEN-END:variables

}
