/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilesTable.java
 *
 * Created on 09-Jun-2010, 13:27:28
 */
package org.jpowder;

import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;
import org.jpowder.Analysis.Jpowder_Reader;
import org.jpowder.dataset.DataSet;
import org.jpowder.fileCabinet.PowderFileCabinet;

/**
 *
 * @author qyt21516
 */
public class FilesTable extends javax.swing.JFrame {

    private static DefaultTableModel defaultTableModel;
    JFileChooser chooser = new JFileChooser(new File("C:/Documents and Settings/qyt21516/Desktop/My Dropbox"));
    Vector<String> columnNames = new Vector<String>();
    Vector<String> row = new Vector<String>();
    DataVisibleInChart dataVisibleInChart = new DataVisibleInChart();
    private static File afile;

    /** Creates new form FilesTable */
    public FilesTable() {


        if (defaultTableModel != null) {
            defaultTableModel.getDataVector().removeAllElements();//remove all the rows from table
            }
        columnNames.add("Name");
        columnNames.add("Size");
        columnNames.add("Type");
        columnNames.add("Date Modified");
        columnNames.add("File");
//        rowData.addElement(getFileName());
        defaultTableModel = new DefaultTableModel(row, columnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 0 || column == 1 || column == 2 || column == 3) {
                    return false;
                } else {
                    return true;
                }
            }
        };

        initComponents();

    }

    public static File getAFile() {
        return afile;
    }

    public static JRadioButton getfileNum() {
        return fNumbRadioButton;
    }

    public static JRadioButton getTemp() {
        return tRadioButton;
    }

    public static JRadioButton getPressure() {
        return pRadioButton;
    }

    public static DefaultTableModel getDefaultTableModel() {
        return defaultTableModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        XAxisUnitPanel = new javax.swing.JPanel();
        fNumbRadioButton = new javax.swing.JRadioButton();
        pRadioButton = new javax.swing.JRadioButton();
        tRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        potButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fileChooserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        XAxisUnitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        buttonGroup1.add(fNumbRadioButton);
        fNumbRadioButton.setSelected(true);
        fNumbRadioButton.setText("jRadioButton1");

        buttonGroup1.add(pRadioButton);
        pRadioButton.setText("jRadioButton2");
        pRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(tRadioButton);
        tRadioButton.setText("jRadioButton3");

        javax.swing.GroupLayout XAxisUnitPanelLayout = new javax.swing.GroupLayout(XAxisUnitPanel);
        XAxisUnitPanel.setLayout(XAxisUnitPanelLayout);
        XAxisUnitPanelLayout.setHorizontalGroup(
            XAxisUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XAxisUnitPanelLayout.createSequentialGroup()
                .addComponent(fNumbRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tRadioButton)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        XAxisUnitPanelLayout.setVerticalGroup(
            XAxisUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XAxisUnitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(XAxisUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNumbRadioButton)
                    .addComponent(pRadioButton)
                    .addComponent(tRadioButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(defaultTableModel);
        jTable1.getColumnModel().removeColumn(jTable1.getColumn("File"));
        jTable1.setDragEnabled(true);
        jTable1.setDropMode(javax.swing.DropMode.INSERT);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(90, 145, 233));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        potButton.setText("Get Plot");
        potButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Remove Selected Row");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fileChooserButton.setText("ImportFiles");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(potButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(XAxisUnitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(XAxisUnitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy HH:mm:ss");
        chooser.setMultiSelectionEnabled(true);

        chooser.showOpenDialog(chooser);

        for (int i = 0; i < chooser.getSelectedFiles().length; i++) {
            row = new Vector<String>();

            row.add(chooser.getSelectedFiles()[i].getName());
            row.add(String.valueOf(chooser.getSelectedFiles()[i].length() / 1024) + " KB");
            row.add(chooser.getTypeDescription(chooser.getSelectedFiles()[i]));
            row.add(dateFormat.format(new Date(chooser.getSelectedFiles()[i].lastModified())));
            row.add(chooser.getSelectedFiles()[i].toString());

            defaultTableModel.addRow(row);
        }


    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void potButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potButtonActionPerformed

        Jpowder.getChartPlotter().remove(Jpowder.getMessageLabel());
        Vector<DataSet> datasets = new Vector<DataSet>();
        HashMap<String, File> hashMap = new LinkedHashMap<String, File>();
        PowderFileCabinet mPowderFileCabinet = new PowderFileCabinet();

        String fileName;



        // loop over the selected file

        for (int i = 0, n = defaultTableModel.getRowCount(); i < n; i++) {
            afile = new File(String.valueOf(defaultTableModel.getValueAt(i, 4)));
            fileName = afile.getName();
            if (fileName.endsWith(".jpowder")) {
                Jpowder_Reader.read(afile);


//                int size = Jpowder_Reader.getLocalData().size();
//                for (int h = 0; h < size; h++) {
//                    System.out.println(Jpowder_Reader.getLocalData().get(h).get(1));
//                }


                fNumbRadioButton.setText(Jpowder_Reader.getLabel().elementAt(0));
                pRadioButton.setText(Jpowder_Reader.getLabel().elementAt(1));
                tRadioButton.setText(Jpowder_Reader.getLabel().elementAt(2));



            }
            if (!fileName.endsWith(".jpowder")) {

                hashMap.put(fileName, afile.getAbsoluteFile());
            }
        }//for



        for (Map.Entry<String, File> entry : hashMap.entrySet()) {
            fileName = entry.getKey();
            afile = entry.getValue();
            if (mPowderFileCabinet.checkAcceptedFileType(fileName)) {

                Vector<DataSet> allDatasets = PowderFileCabinet.createDataSetFromPowderFile(afile.getAbsoluteFile());
                if (allDatasets == null) {
                    return;
                }
                for (int iSet = 0; iSet < allDatasets.size(); iSet++) {
                    DataSet oneDataset = allDatasets.elementAt(iSet);
                    if (oneDataset != null) {
                        datasets.add(oneDataset);
                    }
                }



            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Only ASCII file please.");
                break;
            }

        }

        // finally plot the data
        JpowderInternalframe internalframe = new JpowderInternalframe(dataVisibleInChart, datasets);
        Jpowder.jpowderInternalFrameUpdate(internalframe);

        InternalFrameListener internalFrameListener = new InternalFrameIconifyListener(dataVisibleInChart);
        internalframe.addInternalFrameListener(internalFrameListener);
        Jpowder.getChartPlotter().add(internalframe);
        setVisible(true);
//
//                for(int i=0;i<defaultTableModel.getRowCount();i++){
//                System.out.println(defaultTableModel.getValueAt(i, 0));
//                File f = new File(String.valueOf(defaultTableModel.getValueAt(i, 4)));
//                    System.out.println(f.getAbsoluteFile());
//        System.out.println(defaultTableModel.getDataVector().get(i));
//                }
// Jpowder3DSecondTest dSecondTest= new Jpowder3DSecondTest("");

        JInternalFrame frame = new JInternalFrame("XYZ");
        frame.add(Jpowder3DSecondTest.createDemoPanel());
        frame.setSize(internalframe.getSize());
        frame.setLocation(500, 300);
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setMaximizable(true);
        frame.setIconifiable(true);
        frame.setVisible(true);

        Jpowder.getChartPlotter().add(frame);

        setVisible(true);
    }//GEN-LAST:event_potButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (defaultTableModel.getColumnCount() - 1 != 0) {
            defaultTableModel.removeRow(jTable1.getSelectedRow());
            System.out.println(defaultTableModel.getRowCount() - 1);
            jTable1.setRowSelectionInterval(defaultTableModel.getRowCount() - 1, defaultTableModel.getRowCount() - 1);
        } else {
            return;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pRadioButtonActionPerformed
        System.out.println(Jpowder_Reader.getLocalData().get(1));

    }//GEN-LAST:event_pRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FilesTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FilesTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel XAxisUnitPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JRadioButton fNumbRadioButton;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JRadioButton pRadioButton;
    private javax.swing.JButton potButton;
    private static javax.swing.JRadioButton tRadioButton;
    // End of variables declaration//GEN-END:variables
}
