/* ===========================================================
 * This file is part of Jpowder, see <http://www.jpowder.org/>
 * ===========================================================
 *
 * Jpowder is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jpowder is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ---------
 * AnnotationPanel.java
 *
 * Created on June 28, 2012, 3:54:44 PM
 * ---------
 * (C) Copyright 2009-2010 STFC Rutherford Appleton Laboratories and
 * Kasem Bundit University.
 *
 * Author(s):  Kreecha Puphaiboon, Computer Science Lecturer, Kasem Bundit University
 * Created on 30-Jun-2012, 13:16:21
 *
 * File change history is stored at: <http://code.google.com/p/jpowder/source/browse>
 *
 */
package org.jpowder.chartTools;

import org.jpowder.Annotation.IMapObserver;
import org.jpowder.Annotation.IMapSubject;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jpowder.Analysis.ToolsIcon2D;
import org.jpowder.Analysis.ToolsIcon3D;
import org.jpowder.InernalFrame.JpowderInternalframe2D;
import org.jpowder.InernalFrame.JpowderInternalframe3D;
import org.jpowder.InfoPanel;
import org.jpowder.Jpowder;
import org.jpowder.jfreechart.EditAnnotationFrame;

/**
 *
 * Annotaion Tool for 2D/3D plots. It shows/hides the Annotation
 */
public class AnnotationPanel extends javax.swing.JPanel implements InfoPanel, IMapObserver {

    //private ToolsIcon3D toolsIcon3D;
    private ToolsIcon2D toolsIcon2D;
    private Map annoMap;
    private final String strThere = "There are: ";
    private EditAnnotationFrame eaf = EditAnnotationFrame.getInstance();

    public AnnotationPanel(ToolsIcon2D toolsIcon2D) {
        initComponents();
        annoTxt.setVisible(false);
        jLabel2.setVisible(false);
        this.toolsIcon2D = toolsIcon2D;
        annoTxt.setText(strThere + eaf.getAnnoNumber());
        annoMap = eaf.getAnnoMap();
        eaf.addObserver(this);
    }

    /** Creates new form ColorBar */
    public AnnotationPanel(ToolsIcon3D toolsIcon3D) {
        initComponents();
        //this.toolsIcon3D = toolsIcon3D;
    }

    @Override
    public void update() {
    }

    /**
     * whenever the Map is upadted this class will be alerted.
     * @param o
     */
    @Override
    public void updateMap(IMapSubject o) {
        annoMap = o.getStatusUpdate();
        annoTxt.setText(strThere + annoMap.size());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        showRadioButton = new javax.swing.JRadioButton();
        hideRadioButton = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        annoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Setting Annotations");

        buttonGroup1.add(showRadioButton);
        showRadioButton.setText("Show Annotations");
        showRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hideRadioButton);
        hideRadioButton.setSelected(true);
        hideRadioButton.setText("Hide Annotations");
        hideRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideRadioButtonActionPerformed(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.PNG"))); // NOI18N
        backButton.setText("Back");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backButton.setIconTextGap(2);
        backButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        annoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annoTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("annotation(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hideRadioButton)
                    .addComponent(showRadioButton))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(annoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hideRadioButton)
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_backButtonActionPerformed

    private void showRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRadioButtonActionPerformed
        // TODO: Should handle null pointer.
        //2D is in Focused.
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        JpowderInternalframe3D in3DFocus = Jpowder.internalFrameInFocus3D;

        if (inFocus != null) {
            //try {
            annoTxt.setVisible(true);
            jLabel2.setVisible(true);
            annoTxt.setText(strThere + EditAnnotationFrame.getInstance().getCurrentAnnoMapSize());

            String activeFrameName = inFocus.getChartPanel().getName();
            inFocus.showAnnotation(activeFrameName);
            //} catch (NullPointerException e) {
            //System.out.println("inFocus 2D returned null");
            //}

        } else if (in3DFocus != null) {
            //3D is in Focused.
            annoTxt.setVisible(true);
            jLabel2.setVisible(true);
            annoTxt.setText(strThere + EditAnnotationFrame.getInstance().getCurrentAnnoMapSize());

            String activeFrameName = in3DFocus.getChartPanel().getName();
            in3DFocus.showAnnotation(activeFrameName);

        } else {
            JOptionPane.showMessageDialog(null, "There is no file plotted yet.");
        }


    }//GEN-LAST:event_showRadioButtonActionPerformed

    private void hideRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideRadioButtonActionPerformed
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        annoTxt.setVisible(false);
        jLabel2.setVisible(false);
        //inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.BOTTOM);
    }//GEN-LAST:event_hideRadioButtonActionPerformed

    private void annoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annoTxtActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annoTxt;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton hideRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton showRadioButton;
    // End of variables declaration//GEN-END:variables
}
