/* ===========================================================
 * This file is part of Jpowder, see <http://www.jpowder.org/>
 * ===========================================================
 *
 * Jpowder is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jpowder is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ---------
 * ChangePlotStyle.java
 * ---------
 * (C) Copyright 2009-2010 STFC Rutherford Appleton Laboratories and
 * Kasem Bundit University.
 *
 * Author(s):  M Arjeneh, ISIS, Rutherford Appleton Laboratory
 *             Anders Marvardsen, ISIS, Rutherford Appleton Laboratory
 *
 * File change history is stored at: <http://code.google.com/p/jpowder/source/browse>
 *
 */
package org.jpowder.chartTools;

import java.awt.BasicStroke;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import org.jfree.chart.renderer.xy.XYErrorRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jpowder.Analysis.ToolsIcon2D;
import org.jpowder.InfoPanel;
import org.jpowder.Jpowder;
import org.jpowder.InternalFrame.JpowderInternalframe2D;
import org.jpowder.chartTools.Markers.MarkerArray;
import org.jpowder.chartTools.Markers.MarkerComboBoxRenderer;
import org.jpowder.chartTools.Markers.MarkerShapes;
import org.jpowder.chartTools.Markers.MarkesIcons;
import org.jpowder.dataset.DataSetNoErrors;
import org.jpowder.dataset.DataSetWithErrors;

/**
 *Change the appearnce of each plots within the chart.
 * 
 */
public class ChangePlotStyle extends javax.swing.JPanel implements InfoPanel {

    private ToolsIcon2D toolsIcon;
    /*Array of string which contains the all the file names that have been plotted. */
    private String[] string;
    /* Using Multi line jLabel.*/
    private String labelText =
            "<html><FONT COLOR=RED>Red</FONT> and " +
            "<FONT COLOR=BLUE>Blue</FONT> Text</html>";
    MarkerArray array = new MarkerArray();
    MarkesIcons[] carray = array.createCountriesArray();

    /**
     *
     * @param analysisIcon
     */
    public ChangePlotStyle(ToolsIcon2D analysisIcon) {
        initComponents();
        this.toolsIcon = analysisIcon;

        markersComboBox.setRenderer(new MarkerComboBoxRenderer(null));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        seriesPaintPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dataSetComboBox1 = new javax.swing.JComboBox();
        buttonGroup2 = new javax.swing.ButtonGroup();
        backButton = new javax.swing.JButton();
        changePlotStyleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        markerPanel = new javax.swing.JPanel();
        automaticRadioButton = new javax.swing.JRadioButton();
        noneRadioButton = new javax.swing.JRadioButton();
        buitInRadioButton = new javax.swing.JRadioButton();
        markerBuiltInOption = new javax.swing.JPanel();
        unfillRadioButton = new javax.swing.JRadioButton();
        fillRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        markersComboBox = new javax.swing.JComboBox(carray);
        jLabel5 = new javax.swing.JLabel();
        MarkerSizeSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        fileNameComboBox = new javax.swing.JComboBox();
        seriesColourPanel = new javax.swing.JPanel();
        seriesColourComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        colourPickerButton = new javax.swing.JToggleButton();
        errorBars = new javax.swing.JCheckBox();
        conectingLines = new javax.swing.JCheckBox();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        seriesPaintPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Series Colour"));

        jLabel6.setText("Plot(s):");

        dataSetComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSetComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seriesPaintPanelLayout = new javax.swing.GroupLayout(seriesPaintPanel);
        seriesPaintPanel.setLayout(seriesPaintPanelLayout);
        seriesPaintPanelLayout.setHorizontalGroup(
            seriesPaintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriesPaintPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataSetComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        seriesPaintPanelLayout.setVerticalGroup(
            seriesPaintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriesPaintPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(seriesPaintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataSetComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.PNG"))); // NOI18N
        backButton.setText("Back");
        backButton.setAlignmentY(0.0F);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backButton.setIconTextGap(2);
        backButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        changePlotStyleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Appearance_Large.png"))); // NOI18N
        changePlotStyleLabel.setPreferredSize(new java.awt.Dimension(300, 144));

        jLabel1.setText("Change appearance of plots in a chart.");

        markerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Marker Options"));

        buttonGroup1.add(automaticRadioButton);
        automaticRadioButton.setText("Automatic");
        automaticRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(noneRadioButton);
        noneRadioButton.setText("None");
        noneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(buitInRadioButton);
        buitInRadioButton.setText("Built In");
        buitInRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buitInRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(unfillRadioButton);
        unfillRadioButton.setText("Unfill");
        unfillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfillRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(fillRadioButton);
        fillRadioButton.setSelected(true);
        fillRadioButton.setText("Fill");
        fillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Markers:");

        markersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markersComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Size:");

        MarkerSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 50.0d, 0.5d));
        MarkerSizeSpinner.setValue(2.0);
        MarkerSizeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MarkerSizeSpinnerStateChanged(evt);
            }
        });

        jLabel3.setText("Plot(s):");

        fileNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout markerBuiltInOptionLayout = new javax.swing.GroupLayout(markerBuiltInOption);
        markerBuiltInOption.setLayout(markerBuiltInOptionLayout);
        markerBuiltInOptionLayout.setHorizontalGroup(
            markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markerBuiltInOptionLayout.createSequentialGroup()
                .addGroup(markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(markerBuiltInOptionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(markerBuiltInOptionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fillRadioButton)
                            .addComponent(unfillRadioButton)
                            .addComponent(MarkerSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(markerBuiltInOptionLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );

        markerBuiltInOptionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MarkerSizeSpinner, markersComboBox});

        markerBuiltInOptionLayout.setVerticalGroup(
            markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markerBuiltInOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fileNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(markersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(markerBuiltInOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MarkerSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unfillRadioButton)
                .addGap(19, 19, 19))
        );

        markerBuiltInOptionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MarkerSizeSpinner, markersComboBox});

        javax.swing.GroupLayout markerPanelLayout = new javax.swing.GroupLayout(markerPanel);
        markerPanel.setLayout(markerPanelLayout);
        markerPanelLayout.setHorizontalGroup(
            markerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markerPanelLayout.createSequentialGroup()
                .addGroup(markerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markerPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(markerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buitInRadioButton)
                            .addComponent(noneRadioButton)
                            .addComponent(automaticRadioButton)))
                    .addGroup(markerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(markerBuiltInOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        markerPanelLayout.setVerticalGroup(
            markerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(automaticRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noneRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buitInRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markerBuiltInOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Marker Type", markerPanel);

        seriesColourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Series Colour"));

        seriesColourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriesColourComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Plot(s):");

        colourPickerButton.setText("Pick Series Colour");
        colourPickerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourPickerButtonActionPerformed(evt);
            }
        });

        errorBars.setText("Turn on the error bars");
        errorBars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorBarsActionPerformed(evt);
            }
        });

        conectingLines.setSelected(true);
        conectingLines.setText("Turn on the connecting lines");
        conectingLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectingLinesActionPerformed(evt);
            }
        });

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.25f), null, Float.valueOf(0.25f)));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jLabel8.setText("Width:");

        javax.swing.GroupLayout seriesColourPanelLayout = new javax.swing.GroupLayout(seriesColourPanel);
        seriesColourPanel.setLayout(seriesColourPanelLayout);
        seriesColourPanelLayout.setHorizontalGroup(
            seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriesColourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seriesColourPanelLayout.createSequentialGroup()
                        .addGroup(seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seriesColourPanelLayout.createSequentialGroup()
                                .addComponent(errorBars)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seriesColourPanelLayout.createSequentialGroup()
                                .addGroup(seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seriesColourPanelLayout.createSequentialGroup()
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(colourPickerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(seriesColourComboBox, 0, 212, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(seriesColourPanelLayout.createSequentialGroup()
                        .addComponent(conectingLines, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        seriesColourPanelLayout.setVerticalGroup(
            seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriesColourPanelLayout.createSequentialGroup()
                .addComponent(conectingLines)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorBars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addGroup(seriesColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesColourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(colourPickerButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plot Colour", seriesColourPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changePlotStyleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(changePlotStyleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this is an update method which updates this info Panel.
     */
    @Override
    public void update() {


        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;


        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() != 0) {
            fileNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(addDataSet()));
            seriesColourComboBox.setModel(new javax.swing.DefaultComboBoxModel(addDataSet()));
            colourPickerButton.setEnabled(true);

        }
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            String labels[] = {"No Chart Added"};
            fileNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(labels));
            seriesColourComboBox.setModel(new javax.swing.DefaultComboBoxModel(labels));
            colourPickerButton.setEnabled(false);
            colourPickerButton.setSelected(false);


            return;
        }

          setMarkerBuildIn();
        XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) inFocus.getXYPlot().getRenderer();


        if (inFocus.getPowderDataSet().get(0) instanceof DataSetWithErrors) {
            XYErrorRenderer renderer1 = (XYErrorRenderer) inFocus.getXYPlot().getRenderer();
            errorBars.setSelected(renderer1.getDrawYError());


        }
        conectingLines.setSelected(renderer.getBaseLinesVisible());

        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            errorBars.setSelected(false);
            conectingLines.setSelected(false);

        }
        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {

            if (inFocus.getPowderDataSet().get(i) instanceof DataSetNoErrors) {
                errorBars.setEnabled(false);
            }
            if (inFocus.getPowderDataSet().get(i) instanceof DataSetWithErrors) {
                errorBars.setEnabled(true);

            }
        }
        if (renderer.getBaseShapesVisible()) {
            automaticRadioButton.setSelected(true);
//            if(automaticRadioButton.isSelected()){
//           automaticRadioButton.setSelected(true);
//
//            }
//            if(buitInRadioButton.isSelected()){
//                buitInRadioButton.setSelected(true);
//            }
        } else if (!renderer.getBaseShapesVisible()) {
            noneRadioButton.setSelected(true);
        }

    }

    /**
     *
     * @return changePlotStyleLabel.
     */
    public JLabel getChangePlotStyleLabel() {
        return changePlotStyleLabel;
    }

    public static JComboBox getSeriesColourComboBox() {
        return seriesColourComboBox;
    }

    public static JSpinner getMarkerSizeSpinner() {
        return MarkerSizeSpinner;
    }

    /**
     * this method get all the plotted files name and add them to the comboBox  and
     * also, render to the comboBox so each indivdual file names has the series color
     * wich was plotted in.
     *
     * @return array of strings which contains all the files which has been plotted.
     */
    public String[] addDataSet() {
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        int size = inFocus.getXYPlot().getDatasetCount();
        string = new String[size];
//        string[0] = "Every";
        for (int i = 0; i < size; i++) {

            string[i] = inFocus.getPowderDataSet().elementAt(i).getFileName();
            ComboBoxRenderer boxRenderer = new ComboBoxRenderer();
            fileNameComboBox.setRenderer(boxRenderer);
            seriesColourComboBox.setRenderer(boxRenderer);
        }
        return string;
    }

  public void setMarkerBuildIn() {
        boolean check = buitInRadioButton.isSelected();
        markerBuiltInOption.setVisible(check);

    }


    public void errorMesage() {
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "There Is No Chart.");
            return;
        }
    }

    public void applyMarkerShape() {
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "There Is No Chart.");

            return;
        }

        int seriescount = inFocus.getXYPlot().getDatasetCount();
        for (int i = 0; i < seriescount; i++) {

            if (inFocus.getPowderDataSet().elementAt(i).getFileName().equals(
                    fileNameComboBox.getSelectedItem())) {


                try {

                    XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) inFocus.getXYPlot().getRenderer(i);
                    renderer.setBaseShapesVisible(true);


                    if (markersComboBox.getSelectedIndex() == 0) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[0]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 1) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[1]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 2) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[2]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 3) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[3]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 4) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[4]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 5) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[5]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 6) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[6]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 7) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[7]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 8) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[8]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 9) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[9]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (markersComboBox.getSelectedIndex() == 10) {
                        renderer.setSeriesShape(0, MarkerShapes.markesShape()[10]);
                        renderer.setBaseShapesFilled(true);

                    }
                    if (unfillRadioButton.isSelected()) {
                        renderer.setBaseShapesFilled(false);
                    }
                    if (fillRadioButton.isSelected()) {
                        renderer.setBaseShapesFilled(true);

                    }

                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Enter Valid Number.");

                }
            }
        }
    }

    /**
     * this methods turns the the connecting lines in the plotted data on and off.
     * @param evt
     */
    private void conectingLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectingLinesActionPerformed
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            conectingLines.setSelected(true);
            return;
        }
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        for (int i = 0; i < inFocus.getPowderDataSet().size(); i++) {
            XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) inFocus.getXYPlot().getRenderer(i);
            boolean status = renderer.getBaseLinesVisible();
            renderer.setBaseLinesVisible(!status);

        }
    }//GEN-LAST:event_conectingLinesActionPerformed
    /**
     * this method turns the error bars int he cif and xye data on and off.
     * @param evt
     */
    private void errorBarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorBarsActionPerformed
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            errorBars.setSelected(true);
            return;
        }
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        for (int i = 0; i < inFocus.getPowderDataSet().size(); i++) {

            if (inFocus.getPowderDataSet().get(i) instanceof DataSetWithErrors) {
                XYErrorRenderer renderer = (XYErrorRenderer) inFocus.getXYPlot().getRenderer(i);
                boolean status = renderer.getDrawYError();
                renderer.setDrawYError(!status);//show opposite Y error bar.
                renderer.setDrawXError(!status);
                renderer.setErrorStroke(new BasicStroke(1f));
            }
        }
    }//GEN-LAST:event_errorBarsActionPerformed
    /**
     * return to the chartToolsPanel.
     * @param evt
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        toolsIcon.add(this);
        toolsIcon.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backButtonActionPerformed

    private void fileNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameComboBoxActionPerformed
        applyMarkerShape();

}//GEN-LAST:event_fileNameComboBoxActionPerformed
    /**
     * this method responsible for gettign action of the comboBoxes and textFied and
     * and appling to the plotted data in the internalframe whcih is in focus.
     * @param evt
     */
    private void buitInRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buitInRadioButtonActionPerformed
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            return;
        }
        setMarkerBuildIn();
    
    }//GEN-LAST:event_buitInRadioButtonActionPerformed

    private void noneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneRadioButtonActionPerformed
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            return;
        }
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        for (int i = 0; i < inFocus.getPowderDataSet().size(); i++) {
            XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) inFocus.getXYPlot().getRenderer(i);
            renderer.setBaseShapesVisible(false);

        }
        setMarkerBuildIn();
      
    }//GEN-LAST:event_noneRadioButtonActionPerformed

    private void automaticRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticRadioButtonActionPerformed
        if (JpowderInternalframe2D.getnumberOfJpowderInternalframe() == 0) {
            return;
        }
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        for (int i = 0; i < inFocus.getPowderDataSet().size(); i++) {
            XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) inFocus.getXYPlot().getRenderer(i);
            renderer.setBaseShapesVisible(true);
        }
setMarkerBuildIn();
   

    }//GEN-LAST:event_automaticRadioButtonActionPerformed

    private void dataSetComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSetComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataSetComboBox1ActionPerformed

    private void seriesColourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriesColourComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seriesColourComboBoxActionPerformed

    private void colourPickerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourPickerButtonActionPerformed
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;
        SeriesColourPicker colourPicker = new SeriesColourPicker();
        colourPickerButton.setSelected(false);
        Jpowder.updateJPowderInternalFrame(inFocus);
    }//GEN-LAST:event_colourPickerButtonActionPerformed

    private void MarkerSizeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MarkerSizeSpinnerStateChanged
        applyMarkerShape();
    }//GEN-LAST:event_MarkerSizeSpinnerStateChanged

    private void markersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markersComboBoxActionPerformed
        applyMarkerShape();
    }//GEN-LAST:event_markersComboBoxActionPerformed

    private void fillRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillRadioButtonActionPerformed
        applyMarkerShape();
    }//GEN-LAST:event_fillRadioButtonActionPerformed

    private void unfillRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfillRadioButtonActionPerformed
        applyMarkerShape();
    }//GEN-LAST:event_unfillRadioButtonActionPerformed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        JpowderInternalframe2D inFocus = Jpowder.internalFrameInFocus2D;

        float seriesWidth = (float) Double.parseDouble(jSpinner2.getValue().toString());
        
        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            inFocus.getXYPlot().getRenderer(i).setSeriesStroke(0, new BasicStroke(seriesWidth));

        }
}//GEN-LAST:event_jSpinner2StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JSpinner MarkerSizeSpinner;
    private javax.swing.JRadioButton automaticRadioButton;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton buitInRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel changePlotStyleLabel;
    private javax.swing.JToggleButton colourPickerButton;
    private javax.swing.JCheckBox conectingLines;
    private javax.swing.JComboBox dataSetComboBox1;
    private javax.swing.JCheckBox errorBars;
    private javax.swing.JComboBox fileNameComboBox;
    private javax.swing.JRadioButton fillRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel markerBuiltInOption;
    private javax.swing.JPanel markerPanel;
    private javax.swing.JComboBox markersComboBox;
    private javax.swing.JRadioButton noneRadioButton;
    private static javax.swing.JComboBox seriesColourComboBox;
    private javax.swing.JPanel seriesColourPanel;
    private javax.swing.JPanel seriesPaintPanel;
    private javax.swing.JRadioButton unfillRadioButton;
    // End of variables declaration//GEN-END:variables
}
