/* ===========================================================
 * This file is part of Jpowder, see <http://www.jpowder.org/>
 * ===========================================================
 *
 * Jpowder is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jpowder is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ---------
 * BlockHeight.java
 * ---------
 * (C) Copyright 2009-2010 STFC Rutherford Appleton Laboratories and
 * Kasem Bundit University.
 *
 * Author(s):  Kreecha Puphaiboon, Computer Science Lecturer, Kasem Bundit University
 *              M Arjeneh, ISIS, Rutherford Appleton Laboratory
 *
 * File change history is stored at: <http://code.google.com/p/jpowder/source/browse>
 *
 */

/*
 * ColorBar3D.java
 *
 * Created on Jul 28, 2010, 3:54:44 PM
 */
package org.jpowder.chartTools;

import java.awt.Color;
import java.util.Collections;
import org.jfree.chart.renderer.GrayPaintScale;
import org.jfree.chart.renderer.PaintScale;
import org.jfree.chart.title.PaintScaleLegend;
import org.jfree.ui.RectangleEdge;
import org.jpowder.Analysis.ToolsIcon3D;
import org.jpowder.InternalFrame.JpowderInternalframe3D;
import org.jpowder.InfoPanel;
import org.jpowder.Jpowder;
import org.jpowder.jfreechart.GreenishPaintScale;
import org.jpowder.jfreechart.JpowderXYBlockRenderer;
import org.jpowder.jfreechart.RainBowPaintScale;

/**
 *
 * first Tools for 3D plot
 */
public class ColorBar3D extends javax.swing.JPanel implements InfoPanel {

    private ToolsIcon3D toolsIcon3D;

    /** Creates new form ColorBar3D */
    public ColorBar3D(ToolsIcon3D toolsIcon3D) {
        initComponents();
        this.toolsIcon3D = toolsIcon3D;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioTop3D = new javax.swing.JRadioButton();
        jRadioButtom3D = new javax.swing.JRadioButton();
        jRadioRight3D = new javax.swing.JRadioButton();
        jRadioLeft3D = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioGrey3D = new javax.swing.JRadioButton();
        jRadioRainbow3D = new javax.swing.JRadioButton();
        jRadioGreen3D = new javax.swing.JRadioButton();

        jLabel1.setText("Setting Colour bar  location");

        buttonGroup1.add(jRadioTop3D);
        jRadioTop3D.setText("Top");
        jRadioTop3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTop3DActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtom3D);
        jRadioButtom3D.setSelected(true);
        jRadioButtom3D.setText("Buttom");
        jRadioButtom3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtom3DActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioRight3D);
        jRadioRight3D.setText("Right");
        jRadioRight3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRight3DActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioLeft3D);
        jRadioLeft3D.setText("Left");
        jRadioLeft3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLeft3DActionPerformed(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.PNG"))); // NOI18N
        backButton.setText("Back");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backButton.setIconTextGap(2);
        backButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Go");
        jButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioGrey3D);
        jRadioGrey3D.setText("Gray Scale");
        jRadioGrey3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGrey3DActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioRainbow3D);
        jRadioRainbow3D.setText("RainBow Scale");
        jRadioRainbow3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRainbow3DActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioGreen3D);
        jRadioGreen3D.setText("Green Scale");
        jRadioGreen3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGreen3DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioLeft3D)
                            .addComponent(jRadioButtom3D)
                            .addComponent(jRadioRight3D)
                            .addComponent(jRadioTop3D))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioGrey3D)
                    .addComponent(jButton1)
                    .addComponent(jRadioRainbow3D)
                    .addComponent(jRadioGreen3D))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jRadioTop3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtom3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioRight3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioLeft3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jRadioGrey3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioRainbow3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioGreen3D)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.setVisible(false);
}//GEN-LAST:event_backButtonActionPerformed

    private void jRadioTop3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTop3DActionPerformed

        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//   renderer.setBlockHeight(10);
//   inFocus.getChart().addLegend(new LegendTitle(renderer));
//   PaintScaleLegend legend = inFocus.getChart().getTitle();
        inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.TOP);
//   renderer.setBlockWidth(WIDTH);
//   renderer.setBlockAnchor(RectangleAnchor.TOP);






    }//GEN-LAST:event_jRadioTop3DActionPerformed

    private void jRadioButtom3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtom3DActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
        inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.BOTTOM);
    }//GEN-LAST:event_jRadioButtom3DActionPerformed

    private void jRadioRight3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRight3DActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
        inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.RIGHT);
    }//GEN-LAST:event_jRadioRight3DActionPerformed

    private void jRadioLeft3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLeft3DActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;

        inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.LEFT);
    }//GEN-LAST:event_jRadioLeft3DActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;

        PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                getSubtitle(0);

        psl.getAxis().setLabel(jTextField1.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioGrey3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGrey3DActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
        JpowderXYBlockRenderer renderer = (JpowderXYBlockRenderer) inFocus.getXYPlot().getRenderer();
        PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                getSubtitle(0);

        psl.getAxis().setLabel(jTextField1.getText());


        double maxY = 0;
        double minY = 0;

        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            maxY = (Double) Collections.max(inFocus.getPowderDataSet().elementAt(i).getY());
            minY = (Double) Collections.min(inFocus.getPowderDataSet().elementAt(i).getY());
//            System.out.println("max y" + maxY);
        }

        PaintScale gr = new GrayPaintScale(minY, maxY);

        psl.setScale(gr);
        renderer.setPaintScale(gr);
    }//GEN-LAST:event_jRadioGrey3DActionPerformed

    private void jRadioRainbow3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRainbow3DActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
        JpowderXYBlockRenderer renderer = (JpowderXYBlockRenderer) inFocus.getXYPlot().getRenderer();
        PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                getSubtitle(0);

        double maxY = 0;
        double minY = 0;

        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            maxY = (Double) Collections.max(inFocus.getPowderDataSet().elementAt(i).getY());
            minY = (Double) Collections.min(inFocus.getPowderDataSet().elementAt(i).getY());
//            System.out.println("max y" + maxY);
        }

//         PaintScale ps = new GrayPaintScale(minY, maxY);
        PaintScale rb = new RainBowPaintScale(minY, maxY, Color.BLACK);
        psl.setScale(rb);
        renderer.setPaintScale(rb);
    }//GEN-LAST:event_jRadioRainbow3DActionPerformed

    private void jRadioGreen3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGreen3DActionPerformed
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
        JpowderXYBlockRenderer renderer = (JpowderXYBlockRenderer) inFocus.getXYPlot().getRenderer();
        PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                getSubtitle(0);

        double maxY = 0;
        double minY = 0;

        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            maxY = (Double) Collections.max(inFocus.getPowderDataSet().elementAt(i).getY());
            minY = (Double) Collections.min(inFocus.getPowderDataSet().elementAt(i).getY());
//            System.out.println("max y" + maxY);
        }
        PaintScale gr = new GreenishPaintScale(maxY);

        psl.setScale(gr);
        renderer.setPaintScale(gr);
    }//GEN-LAST:event_jRadioGreen3DActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtom3D;
    private javax.swing.JRadioButton jRadioGreen3D;
    private javax.swing.JRadioButton jRadioGrey3D;
    private javax.swing.JRadioButton jRadioLeft3D;
    private javax.swing.JRadioButton jRadioRainbow3D;
    private javax.swing.JRadioButton jRadioRight3D;
    private javax.swing.JRadioButton jRadioTop3D;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
    }
}
