/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ColorBar.java
 *
 * Created on Jul 28, 2010, 3:54:44 PM
 */

package org.jpowder.chartTools;

import java.awt.Color;
import java.util.Collections;
import org.jfree.chart.renderer.GrayPaintScale;
import org.jfree.chart.renderer.PaintScale;
import org.jfree.chart.title.PaintScaleLegend;
import org.jfree.ui.RectangleEdge;
import org.jpowder.Analysis.ToolsIcon3D;
import org.jpowder.InernalFrame.JpowderInternalframe3D;
import org.jpowder.InfoPanel;
import org.jpowder.Jpowder;
import org.jpowder.jfreechart.GreenishPaintScale;
import org.jpowder.jfreechart.JpowderXYBlockRenderer;
import org.jpowder.jfreechart.RainBowPaintScale;

/**
 *
 * first Tools for 3D plot
 */
public class ColorBar extends javax.swing.JPanel implements InfoPanel {

    private ToolsIcon3D toolsIcon3D;
    /** Creates new form ColorBar */
    public ColorBar(ToolsIcon3D toolsIcon3D) {
        initComponents();
        this.toolsIcon3D=toolsIcon3D;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();

        jLabel1.setText("Setting Colour bar  location");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Top");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Buttom");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Right");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Left");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.PNG"))); // NOI18N
        backButton.setText("Back");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backButton.setIconTextGap(2);
        backButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Go");
        jButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Gray Scale");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("RainBow Scale");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Green Scale");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.setVisible(false);
}//GEN-LAST:event_backButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
 
        JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//   renderer.setBlockHeight(10);
//   inFocus.getChart().addLegend(new LegendTitle(renderer));
//   PaintScaleLegend legend = inFocus.getChart().getTitle();
   inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.TOP);
//   renderer.setBlockWidth(WIDTH);
//   renderer.setBlockAnchor(RectangleAnchor.TOP);






    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
         inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.BOTTOM);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
            JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
         inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.RIGHT);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
             JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
     
         inFocus.getChart().getSubtitle(0).setPosition(RectangleEdge.LEFT);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
      
         PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                 getSubtitle(0);

         psl.getAxis().setLabel(jTextField1.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
   JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
      JpowderXYBlockRenderer renderer =( JpowderXYBlockRenderer) inFocus.getXYPlot().getRenderer();
         PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                 getSubtitle(0);

         psl.getAxis().setLabel(jTextField1.getText());


        double maxY = 0;
        double minY = 0;

        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            maxY = (Double) Collections.max(inFocus.getPowderDataSet().elementAt(i).getY());
            minY = (Double) Collections.min(inFocus.getPowderDataSet().elementAt(i).getY());
//            System.out.println("max y" + maxY);
        }

         PaintScale gr = new GrayPaintScale(minY, maxY);

         psl.setScale(gr);
         renderer.setPaintScale(gr);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
          JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
      JpowderXYBlockRenderer renderer =(JpowderXYBlockRenderer) inFocus.getXYPlot().getRenderer();
         PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                 getSubtitle(0);
         
        double maxY = 0;
        double minY = 0;

        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            maxY = (Double) Collections.max(inFocus.getPowderDataSet().elementAt(i).getY());
            minY = (Double) Collections.min(inFocus.getPowderDataSet().elementAt(i).getY());
//            System.out.println("max y" + maxY);
        }

//         PaintScale ps = new GrayPaintScale(minY, maxY);
         PaintScale rb = new RainBowPaintScale(minY, maxY, Color.BLACK);
         psl.setScale(rb);
         renderer.setPaintScale(rb);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
                JpowderInternalframe3D inFocus = Jpowder.internalFrameInFocus3D;
//         NumberAxis xAxis = (NumberAxis) inFocus.getXYPlot().getz;
       JpowderXYBlockRenderer renderer =( JpowderXYBlockRenderer) inFocus.getXYPlot().getRenderer();
         PaintScaleLegend psl = (PaintScaleLegend) inFocus.getChart().
                 getSubtitle(0);

        double maxY = 0;
        double minY = 0;

        for (int i = 0; i < inFocus.getXYPlot().getDatasetCount(); i++) {
            maxY = (Double) Collections.max(inFocus.getPowderDataSet().elementAt(i).getY());
            minY = (Double) Collections.min(inFocus.getPowderDataSet().elementAt(i).getY());
//            System.out.println("max y" + maxY);
        } 
         PaintScale gr = new GreenishPaintScale(maxY);

         psl.setScale(gr);
         renderer.setPaintScale(gr);
    }//GEN-LAST:event_jRadioButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        
    }

}
