/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComboBoxWithColourFrames.java
 *
 * Created on 09-Jun-2010, 08:58:46
 */

package org.jpowder.chartTools;

/**
 *
 * @author qyt21516
 */
public class ComboBoxWithColourFrames extends javax.swing.JFrame {

    /** Creates new form ComboBoxWithColourFrames */
    public ComboBoxWithColourFrames() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 56, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

     ColorTable colorTable = new ColorTable();
        System.out.println("combx::"+jComboBox1.getLocation());
        System.out.println("Size"+this.getSize());

colorTable.setLocation((int)jComboBox1.getLocation().getX(),this.getHeight());

System.out.println(jComboBox1.getLocation().getX()+"v"+jComboBox1.getHeight());
     colorTable.setVisible(true);
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBoxWithColourFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables

}
