/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ZoomAndPan.java
 *
 * Created on Dec 17, 2009, 2:53:21 PM
 */
package org.jpowder.chartTools;

import javax.swing.JLabel;
import org.jpowder.InfoPanel;
import org.jpowder.JPowder;
import org.jpowder.JpowderInternalframe;

/**
 *
 * @author Arjeneh
 */
public class ZoomAndPan extends javax.swing.JPanel implements InfoPanel {

    private ChartToolsIcon chartToolsIcon;

    /**
     *
     * @param chartToolsIcon
     */
    public ZoomAndPan(ChartToolsIcon chartToolsIcon) {
        initComponents();
        this.chartToolsIcon = chartToolsIcon;

    }

    public JLabel getZoomLable() {
        return zoomLabel;
    }

    public void update() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    backButt = new javax.swing.JButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    reserButt = new javax.swing.JToggleButton();
    zoomLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setPreferredSize(new java.awt.Dimension(297, 347));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setText("Zoom And Pan");

    backButt.setText("Back");
    backButt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backButtActionPerformed(evt);
      }
    });

    jToggleButton2.setText("pan");

    reserButt.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
    reserButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NewImages/arrowshapes.quad-arrow-callout_26x26.png"))); // NOI18N
    reserButt.setText("Reset");
    reserButt.setToolTipText("Fit plot to original size");
    reserButt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reserButtActionPerformed(evt);
      }
    });

    jTextArea1.setBackground(new java.awt.Color(236, 233, 216));
    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("To zoom in click on the left mouse and drag the mouse across the chart and to move the chart hold Ctrl and left mouse. to reset left mouse and drag to right.");
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.setOpaque(false);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reserButt))
              .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(zoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(192, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGap(118, 118, 118)
        .addComponent(backButt)
        .addContainerGap(111, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(zoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jToggleButton2))
          .addGroup(layout.createSequentialGroup()
            .addComponent(reserButt)
            .addGap(2, 2, 2)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(backButt)
        .addContainerGap(48, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void backButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtActionPerformed
        System.out.println("backbutt has been cliked");
        chartToolsIcon.setComponentZOrder(this, 1);
        chartToolsIcon.add(this);
        chartToolsIcon.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtActionPerformed

    private void reserButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserButtActionPerformed
        JpowderInternalframe inFocus = JPowder.internalFrameInFocus;
        inFocus.getChartPanel().restoreAutoBounds();
//      inFocus.remove(getScrollBar());
        reserButt.setSelected(false);

    }//GEN-LAST:event_reserButtActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton backButt;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JToggleButton reserButt;
  private javax.swing.JLabel zoomLabel;
  // End of variables declaration//GEN-END:variables
}
